### ISSUE TITLE
Setup / Installation fix

### ISSUE THREAD

**Issue by Lamapotato** [luciano7/aoeo#1]
Here how i was able to launch game.

Run AoEO2144.exe
It will download a file called "Launcher.exe" from MS server.
You will need to edit your windows HOSTS file:
Usually, this file is at C:\Windows\System32\drivers\etc
Easiest way to be able to edit it is to search "Notepad" on your start menu, right click notepad and "Run as Administrator". Once Notepad opens, do File->Open and go to the directory above. Switch the file type filter to "All Files" and open HOSTS.
Add a new line to HOSTS:
**127.0.0.1**  www.ageofempiresonline.com
Download Mongoose free edition and place it on the same directory as AoEO2144.exe **and launch it**.
Now start the Launcher.exe file you downloaded earlier. You will eventually get in a loop of launchers.
**Close all the launchers.**
Run AoEOnline.exe -> THIS WILL DOWNLOAD THE GAME.
Once the download is finished then copy the contents of the files directory (in this zip) onto the root of your new Age of Empires Online directory (you know, where you just downloaded it to).
That means: xlive.dll should be on the same folder as Spartan.exe, game.cfg should be inside "startup" and the XML file inside of "data".

**Comment by Hydjo** [comment]
Hello !

I did everything that you said, but when I finally click on Spartan.exe to launch the game, a window appears with the pic of AOEO but an error message says "Game initialization failed. Please run the game from the launcher." So I can only click on OK and then it's closed...
Could you help me? :)

Thanks a lot !

**Comment by ellepereira** [comment]
@Hydjo  it seems like you aren't on version 2044 of the game. Did you make sure the Mongoose step was working?

What does your dirFile.txt say 2044?

**Comment by Lamapotato** [comment]
@luciano7 btw, can you post scenarios that you did (i can't figure out how to activate units other than using trigger effect "unforbid and enable unit")?

**Comment by ellepereira** [comment]
Apparently the triggers are the way to enable units AND the different armors.

I'll post my data extractor stuff to let us get a full list of techs for things.

**Comment by KevinW1998** [comment]
I just like to add that if you use Skype, then you have to deactivate it, because it uses port 80, which Mongoose uses.

PS @luciano7 Will you post an update at neoages?

**Comment by GryphusV** [comment]
https://www.youtube.com/watch?v=89kIHMbfNw0 here is installation tutorial.

**Comment by Lamapotato** [comment]
Editor creates temp file with all triggers information each time you press playtest (C:\Users\%Username%\Documents\Spartan\Trigger), and i think i can write some kind of parser to edit it, but it doesn't matter, because if you edit it, there will be no changes in editor. @luciano7 Can you somehow create a way to change triggers externally or explain how to gain access source code to edit it?

**Comment by ellepereira** [comment]
@Lamapotato you can extract data.bar and get access to the triggers XML file.

**Comment by Lamapotato** [comment]
ohgod 
![image](https://cloud.githubusercontent.com/assets/16478633/16169697/07a02e5e-3540-11e6-80ab-3e06642f919d.png)

**Comment by ellepereira** [comment]
hahaha!

The NO TEXTURE texture.
