### ISSUE TITLE
Scenario Ediotr Issue

### ISSUE THREAD

**Issue by GryphusV** [luciano7/aoeo#2]
Am I doing something wrong or you can't build neither recruit units. Thanks for the answer.

**Comment by ellepereira** [comment]
@GryphusV you need to enable each unit using triggers "enable/disable unit" - unfortunately this is how the server did it to enable units for your scenarios. Server would send a list of techs, you'd start your game with those enabled.

**Comment by GryphusV** [comment]
Is there any tutorial on how to do it or can you write one?
