### ISSUE TITLE
Using latest game version?

### ISSUE THREAD

**Issue by francot514** [luciano7/aoeo#4]
Hi, just found this AOE Online repository and is epic amazing your work, want to ask, if is possible to use latest game version, with this "cracked server"???

**Comment by Nessitro** [comment]
Hey i have this issue i don't know what to do QQ halp :'(
![spartan](https://cloud.githubusercontent.com/assets/21269600/23208235/20f566e2-f8ec-11e6-8645-51af032e61f1.PNG)

---------------------------------------------------------------------
I felt great knowing that someone ( some people ) are doing their best best to bring back AOEO thanks a lot but i really hope you'll be able to support the latest version of the game ( i know that it doesn't have the map editor but all i can do is hope for the best :3 ) good luck

**Comment by francot514** [comment]
Find solution in aoeo4ever forum, seems you dont have updated with project files.
